version: '3'

services:
  mongodb-sb:
    image: mongo:7.0.5
    container_name: mongodb-sb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: srimad-bhagavatam
    volumes:
      - ./data/mongodb:/data/db