kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8084
        hostPort: 8084
        listenAddress: "127.0.0.1"
        protocol: TCP
